baseURL = "https://forestrun.org/"
languageCode = "en-us"
title = "Forest Run Collective"

[params]
  author = "Forest Run Collective"
  description = "Wood-fired sauna & thermal wellness retreat in Camden, Maine"
  email = "cory@forestrun.org"
  phone = "+1-207-###-####"

[outputs]
  home = ["HTML", "JSON"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "Bookings"
    url = "/bookings/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
