

baseURL = "https://forestrun.org/"
languageCode = "en-us"
title = "Forest Run Collective"
theme = "beautifulhugo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  description = "Wood-fired sauna & thermal wellness retreat in Camden, Maine"
  email = "cory@forestrun.org"
  admin_email = "admin@forestrun.org"
  bookings_email = "booking@forestrun.org"
  facebook = "https://www.facebook.com/profile.php?id=100086437062759"
  logo = "images/Logo_Banner.png"
  favicon = "images/Logo_Circle_Black.png"
  banner = "images/Logo_Banner.png"
  subtitle = "Retreat. Recover. Reconnect."
  mainSections = ["services", "bookings", "about"]
  socialShare = true
  readingTime = true
  showRelatedPosts = true
  rss = true
  comments = false

[Params.author]
  name = "Forest Run Collective"

[outputs]
  home = ["HTML"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "Bookings"
    url = "/bookings/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
